### ISSUE TITLE
Deleting with $exists: false condition removes rows that have data

### ISSUE THREAD

**Issue by stefaniabarbu** [maasdi/pentaho-mongodb-delete-plugin#11]
Hi, I've encountered the following problem:

Ex:
﻿﻿I have two rows in the collection for one Company, one that has the fields _id, CompanyId, CompanyName and another that only has _id and CompanyId. 

Having the delete criteria: { "CompanyName" : { "$exists" : false }} it deletes both rows, even the one with CompanyName data. For more details see attach.

Can you please help me with this issue?
Thank you!
![Capture](https://user-images.githubusercontent.com/39769622/81076833-d2526100-8ef4-11ea-9548-951f64786913.PNG)

**Comment by maasdi** [comment]
Hi @stefaniabarbu according to mongodb [documentation](https://docs.mongodb.com/manual/reference/operator/query/exists/#op._S_exists):
$exists matches the documents that contain the field, including documents where the field value is null.

You should try : { "CompanyName" : null}
