### ISSUE TITLE
With latest Mongo Db 3.1.1 delete will not  work as result.LastError() is removed from class.

### ISSUE THREAD

**Issue by sumatipatri** [maasdi/pentaho-mongodb-delete-plugin#2]
With latest Mongod java deiver 3.1.1. Momgo Delete will  not work.

Reason : com.mongodb.WriteResult class LastError() method is removed from class.

**Comment by maasdi** [comment]
There's so many changes MongoDB Java Driver 3.0 compare with 2.x version, so will takes time to implemented.

Regarding that, at this moment MongoDB Delete Plugin only support for MongoDB Java Driver 2.x (The latest release use MongoDB Java Driver 2.13.2)

**Comment by maasdi** [comment]
Fixed at new release 2.0.0
Please install the latest version
