### ISSUE TITLE
不兼容mongo3.x

### ISSUE THREAD

**Issue by luckyxiang2017** [maasdi/pentaho-mongodb-delete-plugin#5]
目前pentaho已经升级到8.0版了，mongo使用3.x驱动
这个项目已经不支持访问3.x认证的数据库了

要尽快修复啊，建议修改成使用mongourl的形式
这样随着版本变迁不需要改动很多，这里面大部分代码是从别的项目拷贝的，实在没有必要

**Comment by guoyiwu** [comment]
已经修复了，可以更新代码再试一下

**Comment by luckyxiang2017** [comment]
Yes, but I've fixed it myself
